window.JP = [
    { "kana": "がっこう", "kanji": "学校", "english": "school", "jlpt": ["jlpt-n5"] },
    { "kana": "かわ", "kanji": "川", "english": "river", "jlpt": ["jlpt-n3", "jlpt-n5"] },
    { "kana": "て", "kanji": "手", "english": "hand", "jlpt": ["jlpt-n5"] },
    { "kana": "と", "kanji": "戸", "english": "door (esp. Japanese-style)", "jlpt": ["jlpt-n5"] },
    { "kana": "めがね", "kanji": "眼鏡", "english": "glasses", "jlpt": ["jlpt-n1", "jlpt-n5"] },
    { "kana": "たばこ", "kanji": "煙草", "english": "tobacco", "jlpt": ["jlpt-n1", "jlpt-n5"] },
    { "kana": "あか", "kanji": "赤", "english": "red", "jlpt": ["jlpt-n5"] },
    { "kana": "しごと", "kanji": "仕事", "english": "work", "jlpt": ["jlpt-n5"] },
    { "kana": "えいご", "kanji": "英語", "english": "English (language)", "jlpt": ["jlpt-n5"] },
    { "kana": "もんだい", "kanji": "問題", "english": "question (e.g. on a test)", "jlpt": ["jlpt-n5"] },
    { "kana": "へや", "kanji": "部屋", "english": "room", "jlpt": ["jlpt-n5"] },
    { "kana": "こども", "kanji": "子供", "english": "child", "jlpt": ["jlpt-n5"] },
    { "kana": "じかん", "kanji": "時間", "english": "time", "jlpt": ["jlpt-n5"] },
    { "kana": "あめ", "kanji": "雨", "english": "rain", "jlpt": ["jlpt-n5"] },
    { "kana": "せんせい", "kanji": "先生", "english": "teacher", "jlpt": ["jlpt-n5"] },
    { "kana": "とし", "kanji": "年", "english": "year", "jlpt": ["jlpt-n5"] },
    { "kana": "てがみ", "kanji": "手紙", "english": "letter", "jlpt": ["jlpt-n5"] },
    { "kana": "でんわ", "kanji": "電話", "english": "telephone call", "jlpt": ["jlpt-n5"] },
    { "kana": "みず", "kanji": "水", "english": "water (esp. cool, fresh water, e.g. drinking water)", "jlpt": ["jlpt-n5"] },
    { "kana": "びょうき", "kanji": "病気", "english": "illness (usu. excluding minor ailments, e.g. common cold)", "jlpt": ["jlpt-n5"] },
    { "kana": "あげる", "kanji": "上げる", "english": "to raise", "jlpt": ["jlpt-n4", "jlpt-n2", "jlpt-n5"] },
    { "kana": "けっこん", "kanji": "結婚", "english": "marriage", "jlpt": ["jlpt-n5"] },
    { "kana": "ことば", "kanji": "言葉", "english": "language", "jlpt": ["jlpt-n5"] },
    { "kana": "め", "kanji": "目", "english": "eye", "jlpt": ["jlpt-n5"] },
    { "kana": "はしる", "kanji": "走る", "english": "to run", "jlpt": ["jlpt-n5"] },
    { "kana": "なまえ", "kanji": "名前", "english": "name", "jlpt": ["jlpt-n5"] },
    { "kana": "りょこう", "kanji": "旅行", "english": "travel", "jlpt": ["jlpt-n5"] },
    { "kana": "みち", "kanji": "道", "english": "road", "jlpt": ["jlpt-n5"] },
    { "kana": "ひこうき", "kanji": "飛行機", "english": "aeroplane", "jlpt": ["jlpt-n5"] },
    { "kana": "えいが", "kanji": "映画", "english": "movie", "jlpt": ["jlpt-n5"] },
    { "kana": "おんがく", "kanji": "音楽", "english": "music", "jlpt": ["jlpt-n5"] },
    { "kana": "き", "kanji": "木", "english": "tree", "jlpt": ["jlpt-n5"] },
    { "kana": "だいがく", "kanji": "大学", "english": "university", "jlpt": ["jlpt-n5"] },
    { "kana": "とけい", "kanji": "時計", "english": "clock", "jlpt": ["jlpt-n5"] },
    { "kana": "かぞく", "kanji": "家族", "english": "family", "jlpt": ["jlpt-n5"] },
    { "kana": "はな", "kanji": "花", "english": "flower", "jlpt": ["jlpt-n5"] },
    { "kana": "ねこ", "kanji": "猫", "english": "cat (esp. the domestic cat, Felis catus)", "jlpt": ["jlpt-n5"] },
    { "kana": "まいにち", "kanji": "毎日", "english": "every day", "jlpt": ["jlpt-n5"] },
    { "kana": "しゅくだい", "kanji": "宿題", "english": "homework", "jlpt": ["jlpt-n5"] },
    { "kana": "ゆき", "kanji": "雪", "english": "snow", "jlpt": ["jlpt-n5"] },
    { "kana": "やま", "kanji": "山", "english": "mountain", "jlpt": ["jlpt-n5"] },
    { "kana": "まど", "kanji": "窓", "english": "window", "jlpt": ["jlpt-n5"] },
    { "kana": "どうぶつ", "kanji": "動物", "english": "animal", "jlpt": ["jlpt-n5"] },
    { "kana": "よる", "kanji": "夜", "english": "evening", "jlpt": ["jlpt-n3", "jlpt-n5"] },
    { "kana": "りょうり", "kanji": "料理", "english": "cooking", "jlpt": ["jlpt-n5"] },
    { "kana": "なつ", "kanji": "夏", "english": "summer", "jlpt": ["jlpt-n5"] },
    { "kana": "しんぶん", "kanji": "新聞", "english": "newspaper", "jlpt": ["jlpt-n5"] },
    { "kana": "こうえん", "kanji": "公園", "english": "(public) park", "jlpt": ["jlpt-n5"] },
    { "kana": "いみ", "kanji": "意味", "english": "meaning", "jlpt": ["jlpt-n5"] },
    { "kana": "じてんしゃ", "kanji": "自転車", "english": "bicycle", "jlpt": ["jlpt-n5"] },
    { "kana": "あし", "kanji": "足", "english": "foot", "jlpt": ["jlpt-n5"] },
    { "kana": "でんしゃ", "kanji": "電車", "english": "train", "jlpt": ["jlpt-n5"] },
    { "kana": "さんぽ", "kanji": "散歩", "english": "walk", "jlpt": ["jlpt-n3", "jlpt-n5"] },
    { "kana": "こえ", "kanji": "声", "english": "voice", "jlpt": ["jlpt-n5"] },
    { "kana": "あさ", "kanji": "朝", "english": "morning", "jlpt": ["jlpt-n5"] },
    { "kana": "うた", "kanji": "歌", "english": "song", "jlpt": ["jlpt-n5"] },
    { "kana": "くつ", "kanji": "靴", "english": "shoe", "jlpt": ["jlpt-n5"] },
    { "kana": "はこ", "kanji": "箱", "english": "box", "jlpt": ["jlpt-n5"] },
    { "kana": "つくえ", "kanji": "机", "english": "desk", "jlpt": ["jlpt-n5"] },
    { "kana": "ぼうし", "kanji": "帽子", "english": "hat", "jlpt": ["jlpt-n5"] },
    { "kana": "うみ", "kanji": "海", "english": "sea", "jlpt": ["jlpt-n5"] },
    { "kana": "じゅぎょう", "kanji": "授業", "english": "lesson", "jlpt": ["jlpt-n5"] },
    { "kana": "ぎんこう", "kanji": "銀行", "english": "bank", "jlpt": ["jlpt-n5"] },
    { "kana": "しゃしん", "kanji": "写真", "english": "photograph", "jlpt": ["jlpt-n5"] },
    { "kana": "ふゆ", "kanji": "冬", "english": "winter", "jlpt": ["jlpt-n5"] },
    { "kana": "むら", "kanji": "村", "english": "village", "jlpt": ["jlpt-n5"] },
    { "kana": "かさ", "kanji": "傘", "english": "umbrella", "jlpt": ["jlpt-n5"] },
    { "kana": "くち", "kanji": "口", "english": "mouth", "jlpt": ["jlpt-n5"] },
    { "kana": "はし", "kanji": "橋", "english": "bridge", "jlpt": ["jlpt-n5"] },
    { "kana": "びょういん", "kanji": "病院", "english": "hospital", "jlpt": ["jlpt-n5"] },
    { "kana": "としょかん", "kanji": "図書館", "english": "library", "jlpt": ["jlpt-n5"] },
    { "kana": "はる", "kanji": "春", "english": "spring", "jlpt": ["jlpt-n5"] },
    { "kana": "かいもの", "kanji": "買い物", "english": "shopping", "jlpt": ["jlpt-n5"] },
    { "kana": "いす", "kanji": "椅子", "english": "chair", "jlpt": ["jlpt-n3", "jlpt-n5"] },
    { "kana": "じどうしゃ", "kanji": "自動車", "english": "car", "jlpt": ["jlpt-n5"] },
    { "kana": "いろ", "kanji": "色", "english": "colour", "jlpt": ["jlpt-n5"] },
    { "kana": "たまご", "kanji": "卵", "english": "eggs", "jlpt": ["jlpt-n5"] },
    { "kana": "にく", "kanji": "肉", "english": "flesh", "jlpt": ["jlpt-n5"] },
    { "kana": "かぜ", "kanji": "風邪", "english": "(common) cold", "jlpt": ["jlpt-n5"] },
    { "kana": "そうじ", "kanji": "掃除", "english": "cleaning", "jlpt": ["jlpt-n5"] },
    { "kana": "かみ", "kanji": "紙", "english": "paper", "jlpt": ["jlpt-n5"] },
    { "kana": "かぎ", "kanji": "鍵", "english": "key", "jlpt": ["jlpt-n3", "jlpt-n5"] },
    { "kana": "ざっし", "kanji": "雑誌", "english": "journal", "jlpt": ["jlpt-n5"] },
    { "kana": "きっぷ", "kanji": "切符", "english": "ticket", "jlpt": ["jlpt-n5"] },
    { "kana": "がいこくじん", "kanji": "外国人", "english": "foreigner", "jlpt": ["jlpt-n5"] },
    { "kana": "さいふ", "kanji": "財布", "english": "purse", "jlpt": ["jlpt-n5"] },
    { "kana": "えんぴつ", "kanji": "鉛筆", "english": "pencil", "jlpt": ["jlpt-n5"] },
    { "kana": "おとな", "kanji": "大人", "english": "adult", "jlpt": ["jlpt-n5"] },
    { "kana": "しお", "kanji": "塩", "english": "salt", "jlpt": ["jlpt-n1", "jlpt-n5"] },
    { "kana": "ちず", "kanji": "地図", "english": "map", "jlpt": ["jlpt-n5"] },
    { "kana": "なつやすみ", "kanji": "夏休み", "english": "summer vacation", "jlpt": ["jlpt-n5"] },
    { "kana": "さとう", "kanji": "砂糖", "english": "sugar", "jlpt": ["jlpt-n5"] },
    { "kana": "いけ", "kanji": "池", "english": "pond", "jlpt": ["jlpt-n5"] },
    { "kana": "ゆうびんきょく", "kanji": "郵便局", "english": "post office", "jlpt": ["jlpt-n5"] },
    { "kana": "きょうしつ", "kanji": "教室", "english": "classroom", "jlpt": ["jlpt-n5"] },
    { "kana": "みみ", "kanji": "耳", "english": "ear", "jlpt": ["jlpt-n5"] },
    { "kana": "だいどころ", "kanji": "台所", "english": "kitchen", "jlpt": ["jlpt-n5"] },
    { "kana": "きって", "kanji": "切手", "english": "stamp (postage)", "jlpt": ["jlpt-n5"] },
    { "kana": "でんき", "kanji": "電気", "english": "electricity", "jlpt": ["jlpt-n5"] },
    { "kana": "は", "kanji": "歯", "english": "tooth", "jlpt": ["jlpt-n5"] },
    { "kana": "は", "kanji": "歯", "english": "tooth", "jlpt": ["jlpt-n5"] },
    { "kana": "こうちゃ", "kanji": "紅茶", "english": "black tea", "jlpt": ["jlpt-n5"] },
    { "kana": "かてい", "kanji": "家庭", "english": "home", "jlpt": ["jlpt-n5"] },
    { "kana": "やさい", "kanji": "野菜", "english": "vegetable", "jlpt": ["jlpt-n5"] },
    { "kana": "ふろ", "kanji": "風呂", "english": "bath", "jlpt": ["jlpt-n3", "jlpt-n5"] },
    { "kana": "げんかん", "kanji": "玄関", "english": "entrance", "jlpt": ["jlpt-n5"] },
    { "kana": "ちかてつ", "kanji": "地下鉄", "english": "subway", "jlpt": ["jlpt-n5"] },
    { "kana": "はな", "kanji": "鼻", "english": "nose", "jlpt": ["jlpt-n5"] },
    { "kana": "みどり", "kanji": "緑", "english": "green", "jlpt": ["jlpt-n5"] },
    { "kana": "ひる", "kanji": "昼", "english": "noon", "jlpt": ["jlpt-n5"] },
    { "kana": "にし", "kanji": "西", "english": "west", "jlpt": ["jlpt-n5"] },
    { "kana": "しろ", "kanji": "白", "english": "white", "jlpt": ["jlpt-n5"] },
    { "kana": "せんたく", "kanji": "洗濯", "english": "washing", "jlpt": ["jlpt-n5"] },
    { "kana": "れいぞうこ", "kanji": "冷蔵庫", "english": "refrigerator", "jlpt": ["jlpt-n5"] },
    { "kana": "みなみ", "kanji": "南", "english": "south", "jlpt": ["jlpt-n5"] },
    { "kana": "かようび", "kanji": "火曜日", "english": "Tuesday", "jlpt": ["jlpt-n5"] },
    { "kana": "きた", "kanji": "北", "english": "north", "jlpt": ["jlpt-n5"] },
    { "kana": "ちゃいろ", "kanji": "茶色", "english": "brown", "jlpt": ["jlpt-n5"] },
    { "kana": "きっさてん", "kanji": "喫茶店", "english": "coffee shop", "jlpt": ["jlpt-n5"] },
    { "kana": "くろ", "kanji": "黒", "english": "black", "jlpt": ["jlpt-n5"] },
    { "kana": "あお", "kanji": "青", "english": "blue", "jlpt": ["jlpt-n5"] },
    { "kana": "くつした", "kanji": "靴下", "english": "socks", "jlpt": ["jlpt-n5"] },
    { "kana": "ふうとう", "kanji": "封筒", "english": "envelope", "jlpt": ["jlpt-n5"] },
    { "kana": "へん", "kanji": "辺", "english": "area", "jlpt": ["jlpt-n5"] },
    { "kana": "きいろ", "kanji": "黄色", "english": "yellow", "jlpt": ["jlpt-n1", "jlpt-n5"] },
    { "kana": "えいがかん", "kanji": "映画館", "english": "movie theatre", "jlpt": ["jlpt-n5"] },
    { "kana": "はし", "kanji": "箸", "english": "chopsticks", "jlpt": ["jlpt-n2", "jlpt-n5"] },
    { "kana": "しょくどう", "kanji": "食堂", "english": "dining room", "jlpt": ["jlpt-n5"] },
    { "kana": "ぎゅうにく", "kanji": "牛肉", "english": "beef", "jlpt": ["jlpt-n5"] },
    { "kana": "こうさてん", "kanji": "交差点", "english": "crossing", "jlpt": ["jlpt-n5"] },
    { "kana": "かんじ", "kanji": "漢字", "english": "kanji", "jlpt": ["jlpt-n5"] },
    { "kana": "ちゃわん", "kanji": "茶碗", "english": "rice bowl", "jlpt": ["jlpt-n2", "jlpt-n5"] },
    { "kana": "くもり", "kanji": "曇り", "english": "cloudiness", "jlpt": ["jlpt-n3", "jlpt-n5"] },
    { "kana": "せびろ", "kanji": "背広", "english": "business suit", "jlpt": ["jlpt-n5"] },
    { "kana": "まんねんひつ", "kanji": "万年筆", "english": "fountain pen", "jlpt": ["jlpt-n5"] },
    { "kana": "はいざら", "kanji": "灰皿", "english": "ashtray", "jlpt": ["jlpt-n1", "jlpt-n5"] },
    { "kana": "たいしかん", "kanji": "大使館", "english": "embassy", "jlpt": ["jlpt-n5"] },
    { "kana": "ぶたにく", "kanji": "豚肉", "english": "pork", "jlpt": ["jlpt-n5"] },
    { "kana": "こうばん", "kanji": "交番", "english": "police box", "jlpt": ["jlpt-n5"] },
    { "kana": "のむ", "kanji": "飲む", "english": "to drink", "jlpt": ["jlpt-n5"] },
    { "kana": "あたま", "kanji": "頭", "english": "head", "jlpt": ["jlpt-n5"] },
    { "kana": "にちようび", "kanji": "日曜日", "english": "Sunday", "jlpt": ["jlpt-n5"] },
    { "kana": "たんじょうび", "kanji": "誕生日", "english": "birthday", "jlpt": ["jlpt-n5"] },
    { "kana": "かわいい", "kanji": "可愛い", "english": "cute", "jlpt": ["jlpt-n1", "jlpt-n5"] },
    { "kana": "かばん", "kanji": "鞄", "english": "bag", "jlpt": ["jlpt-n5"] },
    { "kana": "どようび", "kanji": "土曜日", "english": "Saturday", "jlpt": ["jlpt-n5"] },
    { "kana": "げつようび", "kanji": "月曜日", "english": "Monday", "jlpt": ["jlpt-n5"] },
    { "kana": "きんようび", "kanji": "金曜日", "english": "Friday", "jlpt": ["jlpt-n5"] },
    { "kana": "かびん", "kanji": "花瓶", "english": "(flower) vase", "jlpt": ["jlpt-n5"] },
    { "kana": "ほんだな", "kanji": "本棚", "english": "bookshelves", "jlpt": ["jlpt-n5"] },
    { "kana": "もくようび", "kanji": "木曜日", "english": "Thursday", "jlpt": ["jlpt-n5"] },
    { "kana": "せっけん", "kanji": "石鹸", "english": "soap", "jlpt": ["jlpt-n2", "jlpt-n5"] },
    { "kana": "すいようび", "kanji": "水曜日", "english": "Wednesday", "jlpt": ["jlpt-n5"] },
    { "kana": "あめ", "kanji": "飴", "english": "(hard) candy", "jlpt": ["jlpt-n5"] },
    { "kana": "やおや", "kanji": "八百屋", "english": "greengrocer", "jlpt": ["jlpt-n5"] },
    { "kana": "なる", "kanji": "成る", "english": "to become", "jlpt": ["jlpt-n3", "jlpt-n5"] },
    { "kana": "より", "english": "than", "jlpt": ["jlpt-n5"] },
    { "kana": "いちばん", "kanji": "一番", "english": "number one", "jlpt": ["jlpt-n3", "jlpt-n5"] },
    { "kana": "わたし", "kanji": "私", "english": "I", "jlpt": ["jlpt-n5"] },
    { "kana": "そと", "kanji": "外", "english": "outside", "jlpt": ["jlpt-n5"] },
    { "kana": "あね", "kanji": "姉", "english": "older sister", "jlpt": ["jlpt-n5"] },
    { "kana": "ひゃく", "kanji": "百", "english": "hundred", "jlpt": ["jlpt-n5"] },
    { "kana": "ある", "kanji": "有る", "english": "to be", "jlpt": ["jlpt-n3", "jlpt-n2", "jlpt-n5"] },
    { "kana": "その", "kanji": "其の", "english": "that", "jlpt": ["jlpt-n3", "jlpt-n5"] },
    { "kana": "いう", "kanji": "言う", "english": "to say", "jlpt": ["jlpt-n3", "jlpt-n5"] },
    { "kana": "できる", "kanji": "出来る", "english": "to be able (in a position) to do", "jlpt": ["jlpt-n3", "jlpt-n5"] },
    { "kana": "よい", "kanji": "良い", "english": "good", "jlpt": ["jlpt-n3", "jlpt-n1", "jlpt-n5"] },
    { "kana": "ください", "kanji": "下さい", "english": "please (give me)", "jlpt": ["jlpt-n5"] },
    { "kana": "みる", "kanji": "見る", "english": "to see", "jlpt": ["jlpt-n5"] },
    { "kana": "この", "kanji": "此の", "english": "this", "jlpt": ["jlpt-n3", "jlpt-n1", "jlpt-n5"] },
    { "kana": "じぶん", "kanji": "自分", "english": "myself", "jlpt": ["jlpt-n5"] },
    { "kana": "しる", "kanji": "知る", "english": "to know", "jlpt": ["jlpt-n5"] },
    { "kana": "もつ", "kanji": "持つ", "english": "to hold (in one's hand)", "jlpt": ["jlpt-n5"] },
    { "kana": "なに", "kanji": "何", "english": "what", "jlpt": ["jlpt-n3", "jlpt-n5"] },
    { "kana": "くるま", "kanji": "車", "english": "car", "jlpt": ["jlpt-n5"] },
    { "kana": "はなす", "kanji": "話す", "english": "to talk", "jlpt": ["jlpt-n5"] },
    { "kana": "いま", "kanji": "今", "english": "now", "jlpt": ["jlpt-n5"] },
    { "kana": "きょう", "kanji": "今日", "english": "today", "jlpt": ["jlpt-n3", "jlpt-n5"] },
    { "kana": "かう", "kanji": "買う", "english": "to buy", "jlpt": ["jlpt-n5"] },
    { "kana": "よむ", "kanji": "読む", "english": "to read", "jlpt": ["jlpt-n5"] },
    { "kana": "みんな", "kanji": "皆", "english": "everyone", "jlpt": ["jlpt-n4", "jlpt-n3", "jlpt-n5"] },
    { "kana": "あたらしい", "kanji": "新しい", "english": "new", "jlpt": ["jlpt-n5"] },
    { "kana": "はなし", "kanji": "話", "english": "talk", "jlpt": ["jlpt-n5"] },
    { "kana": "あした", "kanji": "明日", "english": "tomorrow", "jlpt": ["jlpt-n4", "jlpt-n5"] },
    { "kana": "きのう", "kanji": "昨日", "english": "yesterday", "jlpt": ["jlpt-n5"] },
    { "kana": "でる", "kanji": "出る", "english": "to leave", "jlpt": ["jlpt-n5"] },
    { "kana": "べんきょう", "kanji": "勉強", "english": "study", "jlpt": ["jlpt-n3", "jlpt-n5"] },
    { "kana": "とる", "kanji": "取る", "english": "to take", "jlpt": ["jlpt-n5"] },
    { "kana": "だれ", "kanji": "誰", "english": "who", "jlpt": ["jlpt-n1", "jlpt-n5"] },
    { "kana": "おかね", "kanji": "お金", "english": "money", "jlpt": ["jlpt-n5"] },
    { "kana": "おとこ", "kanji": "男", "english": "man", "jlpt": ["jlpt-n5"] },
    { "kana": "いぬ", "kanji": "犬", "english": "dog (Canis (lupus) familiaris)", "jlpt": ["jlpt-n5"] },
    { "kana": "つかう", "kanji": "使う", "english": "to use (a tool, method, etc.)", "jlpt": ["jlpt-n5"] },
    { "kana": "たいへん", "kanji": "大変", "english": "very", "jlpt": ["jlpt-n5"] },
    { "kana": "まつ", "kanji": "待つ", "english": "to wait", "jlpt": ["jlpt-n5"] },
    { "kana": "つくる", "kanji": "作る", "english": "to make", "jlpt": ["jlpt-n2", "jlpt-n1", "jlpt-n5"] },
    { "kana": "うしろ", "kanji": "後ろ", "english": "back", "jlpt": ["jlpt-n3", "jlpt-n5"] },
    { "kana": "まち", "kanji": "町", "english": "town", "jlpt": ["jlpt-n3", "jlpt-n5"] },
    { "kana": "えき", "kanji": "駅", "english": "railway station", "jlpt": ["jlpt-n5"] },
    { "kana": "すこし", "kanji": "少し", "english": "a little", "jlpt": ["jlpt-n5"] },
    { "kana": "あなた", "kanji": "貴方", "english": "you", "jlpt": ["jlpt-n1", "jlpt-n5"] },
    { "kana": "ほしい", "kanji": "欲しい", "english": "wanting (to have)", "jlpt": ["jlpt-n5"] },
    { "kana": "いく", "kanji": "行く", "english": "to go", "jlpt": ["jlpt-n1", "jlpt-n5"] },
    { "kana": "のる", "kanji": "乗る", "english": "to get on (train, plane, bus, ship, etc.)", "jlpt": ["jlpt-n5"] },
    { "kana": "おおきな", "kanji": "大きな", "english": "big", "jlpt": ["jlpt-n5"] },
    { "kana": "いしゃ", "kanji": "医者", "english": "doctor", "jlpt": ["jlpt-n5"] },
    { "kana": "おわる", "kanji": "終わる", "english": "to end", "jlpt": ["jlpt-n1", "jlpt-n5"] },
    { "kana": "がくせい", "kanji": "学生", "english": "student (esp. a university student)", "jlpt": ["jlpt-n5"] },
    { "kana": "ながい", "kanji": "長い", "english": "long (distance, length)", "jlpt": ["jlpt-n2", "jlpt-n5"] },
    { "kana": "どの", "kanji": "何の", "english": "which", "jlpt": ["jlpt-n1", "jlpt-n5"] },
    { "kana": "また", "kanji": "又", "english": "again", "jlpt": ["jlpt-n3", "jlpt-n5"] },
    { "kana": "くに", "kanji": "国", "english": "country", "jlpt": ["jlpt-n5"] },
    { "kana": "たかい", "kanji": "高い", "english": "high", "jlpt": ["jlpt-n5"] },
    { "kana": "あまり", "kanji": "余り", "english": "remainder", "jlpt": ["jlpt-n3", "jlpt-n1", "jlpt-n5"] },
    { "kana": "むずかしい", "kanji": "難しい", "english": "difficult", "jlpt": ["jlpt-n5"] },
    { "kana": "ともだち", "kanji": "友達", "english": "friend", "jlpt": ["jlpt-n5"] },
    { "kana": "ほんとう", "kanji": "本当", "english": "truth", "jlpt": ["jlpt-n3", "jlpt-n5"] },
    { "kana": "ひとつ", "kanji": "一つ", "english": "one", "jlpt": ["jlpt-n5"] },
    { "kana": "ねる", "kanji": "寝る", "english": "to sleep (lying down)", "jlpt": ["jlpt-n5"] },
    { "kana": "せいと", "kanji": "生徒", "english": "pupil", "jlpt": ["jlpt-n5"] },
    { "kana": "いそがしい", "kanji": "忙しい", "english": "busy", "jlpt": ["jlpt-n5"] },
    { "kana": "りょうしん", "kanji": "両親", "english": "parents", "jlpt": ["jlpt-n5"] },
    { "kana": "およぐ", "kanji": "泳ぐ", "english": "to swim", "jlpt": ["jlpt-n5"] },
    { "kana": "たつ", "kanji": "立つ", "english": "to stand", "jlpt": ["jlpt-n2", "jlpt-n5"] },
    { "kana": "だす", "kanji": "出す", "english": "to take out", "jlpt": ["jlpt-n5"] },
    { "kana": "はやい", "kanji": "早い", "english": "fast", "jlpt": ["jlpt-n5"] },
    { "kana": "たのしい", "kanji": "楽しい", "english": "enjoyable", "jlpt": ["jlpt-n5"] },
    { "kana": "おもしろい", "kanji": "面白い", "english": "interesting", "jlpt": ["jlpt-n1", "jlpt-n5"] },
    { "kana": "え", "kanji": "絵", "english": "picture", "jlpt": ["jlpt-n5"] },
    { "kana": "おんなのこ", "kanji": "女の子", "english": "girl", "jlpt": ["jlpt-n5"] },
    { "kana": "きる", "kanji": "着る", "english": "to wear (from the shoulders down)", "jlpt": ["jlpt-n5"] },
    { "kana": "じょうず", "kanji": "上手", "english": "skillful", "jlpt": ["jlpt-n5"] },
    { "kana": "ふるい", "kanji": "古い", "english": "old", "jlpt": ["jlpt-n5"] },
    { "kana": "つよい", "kanji": "強い", "english": "strong", "jlpt": ["jlpt-n5"] },
    { "kana": "ぜんぶ", "kanji": "全部", "english": "all", "jlpt": ["jlpt-n5"] },
    { "kana": "よぶ", "kanji": "呼ぶ", "english": "to call out (to)", "jlpt": ["jlpt-n5"] },
    { "kana": "ごご", "kanji": "午後", "english": "afternoon", "jlpt": ["jlpt-n5"] },
    { "kana": "かける", "kanji": "掛ける", "english": "to hang up (e.g. a coat, a picture on the wall)", "jlpt": ["jlpt-n4", "jlpt-n5"] },
    { "kana": "じしょ", "kanji": "辞書", "english": "dictionary", "jlpt": ["jlpt-n5"] },
    { "kana": "てんき", "kanji": "天気", "english": "weather", "jlpt": ["jlpt-n5"] },
    { "kana": "からだ", "kanji": "体", "english": "body", "jlpt": ["jlpt-n3", "jlpt-n1", "jlpt-n5"] },
    { "kana": "おおきい", "kanji": "大きい", "english": "big", "jlpt": ["jlpt-n5"] },
    { "kana": "しつもん", "kanji": "質問", "english": "question", "jlpt": ["jlpt-n5"] },
    { "kana": "ゆうべ", "kanji": "夕べ", "english": "evening", "jlpt": ["jlpt-n3", "jlpt-n5"] },
    { "kana": "ゆうめい", "kanji": "有名", "english": "famous", "jlpt": ["jlpt-n5"] },
    { "kana": "あに", "kanji": "兄", "english": "older brother", "jlpt": ["jlpt-n5"] },
    { "kana": "うたう", "kanji": "歌う", "english": "to sing", "jlpt": ["jlpt-n5"] },
    { "kana": "のぼる", "kanji": "上る", "english": "to ascend", "jlpt": ["jlpt-n3", "jlpt-n2", "jlpt-n5"] },
    { "kana": "ふく", "kanji": "服", "english": "clothes (esp. Western clothes)", "jlpt": ["jlpt-n5"] },
    { "kana": "とり", "kanji": "鳥", "english": "bird", "jlpt": ["jlpt-n5"] },
    { "kana": "ときどき", "kanji": "時々", "english": "sometimes", "jlpt": ["jlpt-n5"] },
    { "kana": "いもうと", "kanji": "妹", "english": "younger sister", "jlpt": ["jlpt-n5"] },
    { "kana": "ふたつ", "kanji": "二つ", "english": "two", "jlpt": ["jlpt-n5"] },
    { "kana": "たのむ", "kanji": "頼む", "english": "to request", "jlpt": ["jlpt-n5"] },
    { "kana": "おとうさん", "kanji": "お父さん", "english": "father", "jlpt": ["jlpt-n5"] },
    { "kana": "けさ", "kanji": "今朝", "english": "this morning", "jlpt": ["jlpt-n5"] },
    { "kana": "おそい", "kanji": "遅い", "english": "slow", "jlpt": ["jlpt-n5"] },
    { "kana": "くすり", "kanji": "薬", "english": "medicine", "jlpt": ["jlpt-n5"] },
    { "kana": "かりる", "kanji": "借りる", "english": "to borrow", "jlpt": ["jlpt-n5"] },
    { "kana": "にわ", "kanji": "庭", "english": "garden", "jlpt": ["jlpt-n5"] },
    { "kana": "がいこく", "kanji": "外国", "english": "foreign country", "jlpt": ["jlpt-n5"] },
    { "kana": "げんき", "kanji": "元気", "english": "lively", "jlpt": ["jlpt-n5"] },
    { "kana": "ちいさい", "kanji": "小さい", "english": "small", "jlpt": ["jlpt-n5"] },
    { "kana": "おとうと", "kanji": "弟", "english": "younger brother", "jlpt": ["jlpt-n1", "jlpt-n5"] },
    { "kana": "さかな", "kanji": "魚", "english": "fish", "jlpt": ["jlpt-n3", "jlpt-n5"] },
    { "kana": "ことし", "kanji": "今年", "english": "this year", "jlpt": ["jlpt-n5"] },
    { "kana": "おかあさん", "kanji": "お母さん", "english": "mother", "jlpt": ["jlpt-n5"] },
    { "kana": "おとこのこ", "kanji": "男の子", "english": "boy", "jlpt": ["jlpt-n5"] },
    { "kana": "とぶ", "kanji": "飛ぶ", "english": "to fly", "jlpt": ["jlpt-n2", "jlpt-n5"] },
    { "kana": "うる", "kanji": "売る", "english": "to sell", "jlpt": ["jlpt-n5"] },
    { "kana": "しずか", "kanji": "静か", "english": "quiet", "jlpt": ["jlpt-n5"] },
    { "kana": "やすむ", "kanji": "休む", "english": "to be absent", "jlpt": ["jlpt-n5"] },
    { "kana": "たべもの", "kanji": "食べ物", "english": "food", "jlpt": ["jlpt-n5"] },
    { "kana": "たいせつ", "kanji": "大切", "english": "important", "jlpt": ["jlpt-n5"] },
    { "kana": "らいしゅう", "kanji": "来週", "english": "next week", "jlpt": ["jlpt-n5"] },
    { "kana": "けいかん", "kanji": "警官", "english": "police officer", "jlpt": ["jlpt-n5"] },
    { "kana": "たてもの", "kanji": "建物", "english": "building", "jlpt": ["jlpt-n5"] },
    { "kana": "あたたかい", "kanji": "暖かい", "english": "warm", "jlpt": ["jlpt-n3", "jlpt-n5"] },
    { "kana": "おりる", "kanji": "降りる", "english": "to descend (e.g. a mountain)", "jlpt": ["jlpt-n4", "jlpt-n5"] },
    { "kana": "とまる", "kanji": "止まる", "english": "to stop (moving)", "jlpt": ["jlpt-n2", "jlpt-n5"] },
    { "kana": "いっしょ", "kanji": "一緒", "english": "together", "jlpt": ["jlpt-n5"] },
    { "kana": "せんしゅう", "kanji": "先週", "english": "last week", "jlpt": ["jlpt-n5"] },
    { "kana": "しろい", "kanji": "白い", "english": "white", "jlpt": ["jlpt-n5"] },
    { "kana": "に", "kanji": "二", "english": "two", "jlpt": ["jlpt-n5"] },
    { "kana": "すくない", "kanji": "少ない", "english": "few", "jlpt": ["jlpt-n5"] },
    { "kana": "あかい", "kanji": "赤い", "english": "red", "jlpt": ["jlpt-n5"] },
    { "kana": "あらう", "kanji": "洗う", "english": "to wash", "jlpt": ["jlpt-n5"] },
    { "kana": "きらい", "kanji": "嫌い", "english": "disliked", "jlpt": ["jlpt-n5"] },
    { "kana": "りっぱ", "kanji": "立派", "english": "splendid", "jlpt": ["jlpt-n3", "jlpt-n5"] },
    { "kana": "ひま", "kanji": "暇", "english": "spare time", "jlpt": ["jlpt-n1", "jlpt-n5"] },
    { "kana": "おちゃ", "kanji": "お茶", "english": "tea (usu. green)", "jlpt": ["jlpt-n5"] },
    { "kana": "ひろい", "kanji": "広い", "english": "spacious", "jlpt": ["jlpt-n5"] },
    { "kana": "きょねん", "kanji": "去年", "english": "last year", "jlpt": ["jlpt-n5"] },
    { "kana": "だいすき", "kanji": "大好き", "english": "liking very much", "jlpt": ["jlpt-n5"] },
    { "kana": "となり", "kanji": "隣", "english": "next (to)", "jlpt": ["jlpt-n5"] },
    { "kana": "おんな", "kanji": "女", "english": "female", "jlpt": ["jlpt-n5"] },
    { "kana": "きる", "kanji": "切る", "english": "to cut", "jlpt": ["jlpt-n5"] },
    { "kana": "たぶん", "kanji": "多分", "english": "perhaps", "jlpt": ["jlpt-n3", "jlpt-n5"] },
    { "kana": "いや", "kanji": "嫌", "english": "disagreeable", "jlpt": ["jlpt-n5"] },
    { "kana": "まいあさ", "kanji": "毎朝", "english": "every morning", "jlpt": ["jlpt-n5"] },
    { "kana": "にもつ", "kanji": "荷物", "english": "luggage", "jlpt": ["jlpt-n5"] },
    { "kana": "ばんごう", "kanji": "番号", "english": "number", "jlpt": ["jlpt-n5"] },
    { "kana": "かえす", "kanji": "返す", "english": "to return (something)", "jlpt": ["jlpt-n5"] },
    { "kana": "らいねん", "kanji": "来年", "english": "next year", "jlpt": ["jlpt-n5"] },
    { "kana": "あかるい", "kanji": "明るい", "english": "light", "jlpt": ["jlpt-n1", "jlpt-n5"] },
    { "kana": "ちかい", "kanji": "近い", "english": "near", "jlpt": ["jlpt-n5"] },
    { "kana": "むこう", "kanji": "向こう", "english": "opposite side", "jlpt": ["jlpt-n5"] },
    { "kana": "はじめ", "kanji": "始め", "english": "beginning", "jlpt": ["jlpt-n1", "jlpt-n5"] },
    { "kana": "いたい", "kanji": "痛い", "english": "painful", "jlpt": ["jlpt-n5"] },
    { "kana": "やすみ", "kanji": "休み", "english": "rest", "jlpt": ["jlpt-n5"] },
    { "kana": "れんしゅう", "kanji": "練習", "english": "practice", "jlpt": ["jlpt-n3", "jlpt-n5"] },
    { "kana": "じゅう", "kanji": "十", "english": "ten", "jlpt": ["jlpt-n3", "jlpt-n5"] },
    { "kana": "うわぎ", "kanji": "上着", "english": "coat", "jlpt": ["jlpt-n5"] },
    { "kana": "せんげつ", "kanji": "先月", "english": "last month", "jlpt": ["jlpt-n5"] },
    { "kana": "けっこう", "kanji": "結構", "english": "splendid", "jlpt": ["jlpt-n5"] },
    { "kana": "まいとし", "kanji": "毎年", "english": "every year", "jlpt": ["jlpt-n5"] },
    { "kana": "きょうだい", "kanji": "兄弟", "english": "siblings", "jlpt": ["jlpt-n5"] },
    { "kana": "らいげつ", "kanji": "来月", "english": "next month", "jlpt": ["jlpt-n5"] },
    { "kana": "ご", "kanji": "五", "english": "five", "jlpt": ["jlpt-n5"] },
    { "kana": "のみもの", "kanji": "飲み物", "english": "drink", "jlpt": ["jlpt-n5"] },
    { "kana": "よわい", "kanji": "弱い", "english": "weak", "jlpt": ["jlpt-n5"] },
    { "kana": "ぎゅうにゅう", "kanji": "牛乳", "english": "(cow's) milk", "jlpt": ["jlpt-n5"] },
    { "kana": "さん", "kanji": "三", "english": "three", "jlpt": ["jlpt-n1", "jlpt-n5"] },
    { "kana": "だいじょうぶ", "kanji": "大丈夫", "english": "safe", "jlpt": ["jlpt-n5"] },
    { "kana": "くろい", "kanji": "黒い", "english": "black", "jlpt": ["jlpt-n5"] },
    { "kana": "みなさん", "kanji": "皆さん", "english": "all", "jlpt": ["jlpt-n5"] },
    { "kana": "はんぶん", "kanji": "半分", "english": "half", "jlpt": ["jlpt-n5"] },
    { "kana": "おす", "kanji": "押す", "english": "to push", "jlpt": ["jlpt-n5"] },
    { "kana": "つとめる", "kanji": "勤める", "english": "to work (for)", "jlpt": ["jlpt-n2", "jlpt-n5"] },
    { "kana": "あつい", "kanji": "熱い", "english": "hot (to the touch)", "jlpt": ["jlpt-n5"] },
    { "kana": "みっつ", "kanji": "三つ", "english": "three", "jlpt": ["jlpt-n5"] },
    { "kana": "くだもの", "kanji": "果物", "english": "fruit", "jlpt": ["jlpt-n5"] },
    { "kana": "こんしゅう", "kanji": "今週", "english": "this week", "jlpt": ["jlpt-n5"] },
    { "kana": "あまい", "kanji": "甘い", "english": "sweet-tasting", "jlpt": ["jlpt-n5"] },
    { "kana": "みぎ", "kanji": "右", "english": "right", "jlpt": ["jlpt-n5"] },
    { "kana": "ばん", "kanji": "晩", "english": "evening", "jlpt": ["jlpt-n5"] },
    { "kana": "いくつ", "kanji": "幾つ", "english": "how many", "jlpt": ["jlpt-n3", "jlpt-n5"] },
    { "kana": "かいだん", "kanji": "階段", "english": "stairs", "jlpt": ["jlpt-n5"] },
    { "kana": "おおぜい", "kanji": "大勢", "english": "crowd of people", "jlpt": ["jlpt-n5"] },
    { "kana": "はる", "kanji": "張る", "english": "to stick", "jlpt": ["jlpt-n3", "jlpt-n5"] },
    { "kana": "ゆうがた", "kanji": "夕方", "english": "evening", "jlpt": ["jlpt-n5"] },
    { "kana": "ひくい", "kanji": "低い", "english": "low (rank, degree, value, content, quality, etc.)", "jlpt": ["jlpt-n5"] },
    { "kana": "ひだり", "kanji": "左", "english": "left", "jlpt": ["jlpt-n5"] },
    { "kana": "まいしゅう", "kanji": "毎週", "english": "every week", "jlpt": ["jlpt-n5"] },
    { "kana": "へた", "kanji": "下手", "english": "unskillful", "jlpt": ["jlpt-n5"] },
    { "kana": "せん", "kanji": "千", "english": "1,000", "jlpt": ["jlpt-n5"] },
    { "kana": "わたす", "kanji": "渡す", "english": "to ferry across (e.g. a river)", "jlpt": ["jlpt-n5"] },
    { "kana": "ごぜん", "kanji": "午前", "english": "morning", "jlpt": ["jlpt-n5"] },
    { "kana": "まるい", "kanji": "丸い", "english": "round", "jlpt": ["jlpt-n3", "jlpt-n2", "jlpt-n5"] },
    { "kana": "べんり", "kanji": "便利", "english": "convenient", "jlpt": ["jlpt-n5"] },
    { "kana": "こんげつ", "kanji": "今月", "english": "this month", "jlpt": ["jlpt-n5"] },
    { "kana": "あびる", "kanji": "浴びる", "english": "to dash over oneself (e.g. water)", "jlpt": ["jlpt-n3", "jlpt-n5"] },
    { "kana": "はん", "kanji": "半", "english": "half", "jlpt": ["jlpt-n5"] },
    { "kana": "ようふく", "kanji": "洋服", "english": "Western-style clothes (cf. traditional Japanese clothes)", "jlpt": ["jlpt-n5"] },
    { "kana": "とる", "kanji": "撮る", "english": "to take (a photograph)", "jlpt": ["jlpt-n5"] },
    { "kana": "しめる", "kanji": "締める", "english": "to tie", "jlpt": ["jlpt-n5"] },
    { "kana": "ぶんしょう", "kanji": "文章", "english": "writing", "jlpt": ["jlpt-n5"] },
    { "kana": "はち", "kanji": "八", "english": "eight", "jlpt": ["jlpt-n5"] },
    { "kana": "うすい", "kanji": "薄い", "english": "thin", "jlpt": ["jlpt-n5"] },
    { "kana": "よこ", "kanji": "横", "english": "horizontal (as opposed to vertical)", "jlpt": ["jlpt-n5"] },
    { "kana": "ろく", "kanji": "六", "english": "six", "jlpt": ["jlpt-n1", "jlpt-n5"] },
    { "kana": "よっつ", "kanji": "四つ", "english": "four", "jlpt": ["jlpt-n5"] },
    { "kana": "じょうぶ", "kanji": "丈夫", "english": "healthy", "jlpt": ["jlpt-n5"] },
    { "kana": "まいばん", "kanji": "毎晩", "english": "every night", "jlpt": ["jlpt-n5"] },
    { "kana": "ひがし", "kanji": "東", "english": "east", "jlpt": ["jlpt-n5"] },
    { "kana": "いつつ", "kanji": "五つ", "english": "five", "jlpt": ["jlpt-n5"] },
    { "kana": "はれ", "kanji": "晴れ", "english": "clear weather", "jlpt": ["jlpt-n5"] },
    { "kana": "ほそい", "kanji": "細い", "english": "thin", "jlpt": ["jlpt-n5"] },
    { "kana": "ろうか", "kanji": "廊下", "english": "corridor", "jlpt": ["jlpt-n5"] },
    { "kana": "ふとい", "kanji": "太い", "english": "fat", "jlpt": ["jlpt-n5"] },
    { "kana": "たて", "kanji": "縦", "english": "the vertical", "jlpt": ["jlpt-n3", "jlpt-n5"] },
    { "kana": "ななつ", "kanji": "七つ", "english": "seven", "jlpt": ["jlpt-n5"] },
    { "kana": "ここのつ", "kanji": "九つ", "english": "nine", "jlpt": ["jlpt-n5"] },
    { "kana": "りゅうがくせい", "kanji": "留学生", "english": "overseas student", "jlpt": ["jlpt-n5"] },
    { "kana": "おととし", "kanji": "一昨年", "english": "year before last", "jlpt": ["jlpt-n2", "jlpt-n5"] },
    { "kana": "ひと", "kanji": "人", "english": "person", "jlpt": ["jlpt-n5"] },
    { "kana": "いる", "kanji": "居る", "english": "to be (of animate objects)", "jlpt": ["jlpt-n5"] },
    { "kana": "それ", "kanji": "其れ", "english": "that", "jlpt": ["jlpt-n3", "jlpt-n1", "jlpt-n5"] },
    { "kana": "もの", "kanji": "物", "english": "thing", "jlpt": ["jlpt-n5"] },
    { "kana": "いえ", "kanji": "家", "english": "house", "jlpt": ["jlpt-n5"] },
    { "kana": "ほん", "kanji": "本", "english": "book", "jlpt": ["jlpt-n5"] },
    { "kana": "とても", "kanji": "迚も", "english": "very", "jlpt": ["jlpt-n1", "jlpt-n5"] },
    { "kana": "あう", "kanji": "会う", "english": "to meet", "jlpt": ["jlpt-n2", "jlpt-n5"] },
    { "kana": "すき", "kanji": "好き", "english": "liking", "jlpt": ["jlpt-n5"] },
    { "kana": "わかる", "kanji": "分かる", "english": "to understand", "jlpt": ["jlpt-n2", "jlpt-n5"] },
    { "kana": "これ", "kanji": "此れ", "english": "this", "jlpt": ["jlpt-n1", "jlpt-n5"] },
    { "kana": "きく", "kanji": "聞く", "english": "to hear", "jlpt": ["jlpt-n5"] },
    { "kana": "ところ", "kanji": "所", "english": "place", "jlpt": ["jlpt-n5"] },
    { "kana": "さき", "kanji": "先", "english": "point", "jlpt": ["jlpt-n5"] },
    { "kana": "いつも", "kanji": "何時も", "english": "always", "jlpt": ["jlpt-n3", "jlpt-n1", "jlpt-n5"] },
    { "kana": "かく", "kanji": "書く", "english": "to write", "jlpt": ["jlpt-n5"] },
    { "kana": "たくさん", "kanji": "沢山", "english": "a lot", "jlpt": ["jlpt-n1", "jlpt-n5"] },
    { "kana": "はいる", "kanji": "入る", "english": "to enter", "jlpt": ["jlpt-n5"] },
    { "kana": "おく", "kanji": "置く", "english": "to put", "jlpt": ["jlpt-n5"] },
    { "kana": "どこ", "kanji": "何処", "english": "where", "jlpt": ["jlpt-n1", "jlpt-n5"] },
    { "kana": "すむ", "kanji": "住む", "english": "to live (of humans)", "jlpt": ["jlpt-n5"] },
    { "kana": "たべる", "kanji": "食べる", "english": "to eat", "jlpt": ["jlpt-n5"] },
    { "kana": "あるく", "kanji": "歩く", "english": "to walk", "jlpt": ["jlpt-n5"] },
    { "kana": "はたらく", "kanji": "働く", "english": "to work", "jlpt": ["jlpt-n5"] },
    { "kana": "つく", "kanji": "着く", "english": "to arrive at", "jlpt": ["jlpt-n5"] },
    { "kana": "うえ", "kanji": "上", "english": "above", "jlpt": ["jlpt-n5"] },
    { "kana": "わるい", "kanji": "悪い", "english": "bad", "jlpt": ["jlpt-n5"] },
    { "kana": "おしえる", "kanji": "教える", "english": "to teach", "jlpt": ["jlpt-n5"] },
    { "kana": "ふる", "kanji": "降る", "english": "to fall (of rain, snow, ash, etc.)", "jlpt": ["jlpt-n5"] },
    { "kana": "しぬ", "kanji": "死ぬ", "english": "to die", "jlpt": ["jlpt-n5"] },
    { "kana": "かえる", "kanji": "帰る", "english": "to return", "jlpt": ["jlpt-n5"] },
    { "kana": "わすれる", "kanji": "忘れる", "english": "to forget", "jlpt": ["jlpt-n5"] },
    { "kana": "おおい", "kanji": "多い", "english": "many", "jlpt": ["jlpt-n5"] },
    { "kana": "でかける", "kanji": "出かける", "english": "to go out (e.g. on an excursion or outing)", "jlpt": ["jlpt-n2", "jlpt-n5"] },
    { "kana": "わかい", "kanji": "若い", "english": "young", "jlpt": ["jlpt-n5"] },
    { "kana": "かかる", "kanji": "掛かる", "english": "to take (a resource, e.g. time or money)", "jlpt": ["jlpt-n3", "jlpt-n5"] },
    { "kana": "おなじ", "kanji": "同じ", "english": "same", "jlpt": ["jlpt-n5"] },
    { "kana": "おきる", "kanji": "起きる", "english": "to get up", "jlpt": ["jlpt-n5"] },
    { "kana": "すわる", "kanji": "座る", "english": "to sit", "jlpt": ["jlpt-n5"] },
    { "kana": "みせ", "kanji": "店", "english": "store", "jlpt": ["jlpt-n5"] },
    { "kana": "いれる", "kanji": "入れる", "english": "to put in", "jlpt": ["jlpt-n5"] },
    { "kana": "どなた", "kanji": "何方", "english": "who", "jlpt": ["jlpt-n1", "jlpt-n5"] },
    { "kana": "ちょっと", "kanji": "一寸", "english": "a little", "jlpt": ["jlpt-n1", "jlpt-n5"] },
    { "kana": "つかれる", "kanji": "疲れる", "english": "to get tired", "jlpt": ["jlpt-n5"] },
    { "kana": "あける", "kanji": "開ける", "english": "to open (a door, etc.)", "jlpt": ["jlpt-n3", "jlpt-n5"] },
    { "kana": "なぜ", "kanji": "何故", "english": "why", "jlpt": ["jlpt-n1", "jlpt-n5"] },
    { "kana": "いちにち", "kanji": "一日", "english": "one day", "jlpt": ["jlpt-n1", "jlpt-n5"] },
    { "kana": "さむい", "kanji": "寒い", "english": "cold (e.g. weather)", "jlpt": ["jlpt-n5"] },
    { "kana": "みせる", "kanji": "見せる", "english": "to show", "jlpt": ["jlpt-n5"] },
    { "kana": "ちがう", "kanji": "違う", "english": "to differ (from)", "jlpt": ["jlpt-n5"] },
    { "kana": "どうして", "kanji": "如何して", "english": "how", "jlpt": ["jlpt-n1", "jlpt-n5"] },
    { "kana": "つける", "kanji": "付ける", "english": "to attach", "jlpt": ["jlpt-n3", "jlpt-n2", "jlpt-n5"] },
    { "kana": "おぼえる", "kanji": "覚える", "english": "to memorize", "jlpt": ["jlpt-n5"] },
    { "kana": "ちかく", "kanji": "近く", "english": "near", "jlpt": ["jlpt-n5"] },
    { "kana": "かぜ", "kanji": "風", "english": "wind", "jlpt": ["jlpt-n5"] },
    { "kana": "こまる", "kanji": "困る", "english": "to be troubled", "jlpt": ["jlpt-n5"] },
    { "kana": "うまれる", "kanji": "生まれる", "english": "to be born", "jlpt": ["jlpt-n5"] },
    { "kana": "ちょうど", "kanji": "丁度", "english": "exactly", "jlpt": ["jlpt-n1", "jlpt-n5"] },
    { "kana": "はじめて", "kanji": "初めて", "english": "for the first time", "jlpt": ["jlpt-n5"] },
    { "kana": "はじまる", "kanji": "始まる", "english": "to begin", "jlpt": ["jlpt-n5"] },
    { "kana": "かす", "kanji": "貸す", "english": "to lend", "jlpt": ["jlpt-n5"] },
    { "kana": "きれい", "kanji": "綺麗", "english": "pretty", "jlpt": ["jlpt-n1", "jlpt-n5"] },
    { "kana": "いくら", "kanji": "幾ら", "english": "how much", "jlpt": ["jlpt-n3", "jlpt-n5"] },
    { "kana": "そら", "kanji": "空", "english": "sky", "jlpt": ["jlpt-n5"] },
    { "kana": "ひく", "kanji": "弾く", "english": "to play (a stringed or keyboard instrument)", "jlpt": ["jlpt-n5"] },
    { "kana": "あつい", "kanji": "暑い", "english": "hot", "jlpt": ["jlpt-n5"] },
    { "kana": "あそぶ", "kanji": "遊ぶ", "english": "to play (games, sports)", "jlpt": ["jlpt-n5"] },
    { "kana": "しかし", "kanji": "然し", "english": "however", "jlpt": ["jlpt-n1", "jlpt-n5"] },
    { "kana": "なくす", "kanji": "無くす", "english": "to lose (something)", "jlpt": ["jlpt-n2", "jlpt-n5"] },
    { "kana": "いろいろ", "kanji": "色々", "english": "various", "jlpt": ["jlpt-n1", "jlpt-n5"] },
    { "kana": "わたる", "kanji": "渡る", "english": "to cross over", "jlpt": ["jlpt-n5"] },
    { "kana": "くらい", "kanji": "暗い", "english": "dark", "jlpt": ["jlpt-n5"] },
    { "kana": "こちら", "kanji": "此方", "english": "this way", "jlpt": ["jlpt-n5"] },
    { "kana": "おもい", "kanji": "重い", "english": "heavy", "jlpt": ["jlpt-n5"] },
    { "kana": "こんばん", "kanji": "今晩", "english": "tonight", "jlpt": ["jlpt-n5"] },
    { "kana": "おいしい", "kanji": "美味しい", "english": "good(-tasting)", "jlpt": ["jlpt-n1", "jlpt-n5"] },
    { "kana": "けす", "kanji": "消す", "english": "to erase", "jlpt": ["jlpt-n5"] },
    { "kana": "やさしい", "kanji": "易しい", "english": "easy", "jlpt": ["jlpt-n5"] },
    { "kana": "しめる", "kanji": "閉める", "english": "to close", "jlpt": ["jlpt-n5"] },
    { "kana": "やすい", "kanji": "安い", "english": "cheap", "jlpt": ["jlpt-n5"] },
    { "kana": "とおい", "kanji": "遠い", "english": "far", "jlpt": ["jlpt-n5"] },
    { "kana": "みじかい", "kanji": "短い", "english": "short", "jlpt": ["jlpt-n5"] },
    { "kana": "はれる", "kanji": "晴れる", "english": "to clear up", "jlpt": ["jlpt-n5"] },
    { "kana": "まがる", "kanji": "曲がる", "english": "to bend", "jlpt": ["jlpt-n1", "jlpt-n5"] },
    { "kana": "きえる", "kanji": "消える", "english": "to disappear", "jlpt": ["jlpt-n5"] },
    { "kana": "つめたい", "kanji": "冷たい", "english": "cold (to the touch)", "jlpt": ["jlpt-n5"] },
    { "kana": "あおい", "kanji": "青い", "english": "blue", "jlpt": ["jlpt-n5"] },
    { "kana": "ふく", "kanji": "吹く", "english": "to blow (of the wind)", "jlpt": ["jlpt-n5"] },
    { "kana": "ページ", "kanji": "頁", "english": "page", "jlpt": ["jlpt-n5"] },
    { "kana": "おくさん", "kanji": "奥さん", "english": "wife", "jlpt": ["jlpt-n2", "jlpt-n5"] },
    { "kana": "ひく", "kanji": "引く", "english": "to pull", "jlpt": ["jlpt-n5"] },
    { "kana": "だんだん", "kanji": "段々", "english": "gradually", "jlpt": ["jlpt-n1", "jlpt-n5"] },
    { "kana": "ならう", "kanji": "習う", "english": "to take lessons in", "jlpt": ["jlpt-n5"] },
    { "kana": "あそこ", "kanji": "彼処", "english": "there", "jlpt": ["jlpt-n1", "jlpt-n5"] },
    { "kana": "せまい", "kanji": "狭い", "english": "narrow", "jlpt": ["jlpt-n5"] },
    { "kana": "かるい", "kanji": "軽い", "english": "light (i.e. not heavy)", "jlpt": ["jlpt-n5"] },
    { "kana": "ぬぐ", "kanji": "脱ぐ", "english": "to take off (clothes, shoes, etc.)", "jlpt": ["jlpt-n5"] },
    { "kana": "まん", "kanji": "万", "english": "10,000", "jlpt": ["jlpt-n5"] },
    { "kana": "うるさい", "kanji": "煩い", "english": "noisy", "jlpt": ["jlpt-n1", "jlpt-n5"] },
    { "kana": "ならぶ", "kanji": "並ぶ", "english": "to line up", "jlpt": ["jlpt-n5"] },
    { "kana": "すう", "kanji": "吸う", "english": "to smoke", "jlpt": ["jlpt-n5"] },
    { "kana": "つまらない", "kanji": "詰らない", "english": "dull", "jlpt": ["jlpt-n1", "jlpt-n5"] },
    { "kana": "しまる", "kanji": "閉まる", "english": "to be shut", "jlpt": ["jlpt-n5"] },
    { "kana": "さく", "kanji": "咲く", "english": "to bloom", "jlpt": ["jlpt-n5"] },
    { "kana": "まっすぐ", "kanji": "真っ直ぐ", "english": "straight (ahead)", "jlpt": ["jlpt-n3", "jlpt-n5"] },
    { "kana": "いち", "kanji": "一", "english": "one", "jlpt": ["jlpt-n5"] },
    { "kana": "おばあさん", "kanji": "お祖母さん", "english": "grandmother", "jlpt": ["jlpt-n1", "jlpt-n5"] },
    { "kana": "そちら", "kanji": "其方", "english": "that way", "jlpt": ["jlpt-n1", "jlpt-n5"] },
    { "kana": "すずしい", "kanji": "涼しい", "english": "cool", "jlpt": ["jlpt-n5"] },
    { "kana": "あつい", "kanji": "厚い", "english": "thick", "jlpt": ["jlpt-n5"] },
    { "kana": "おにいさん", "kanji": "お兄さん", "english": "older brother", "jlpt": ["jlpt-n5"] },
    { "kana": "おねえさん", "kanji": "お姉さん", "english": "older sister", "jlpt": ["jlpt-n5"] },
    { "kana": "あぶない", "kanji": "危ない", "english": "dangerous", "jlpt": ["jlpt-n5"] },
    { "kana": "ならべる", "kanji": "並べる", "english": "to line up", "jlpt": ["jlpt-n5"] },
    { "kana": "きたない", "kanji": "汚い", "english": "dirty", "jlpt": ["jlpt-n5"] },
    { "kana": "おなか", "kanji": "お腹", "english": "belly", "jlpt": ["jlpt-n3", "jlpt-n5"] },
    { "kana": "まずい", "kanji": "不味い", "english": "bad (taste)", "jlpt": ["jlpt-n1", "jlpt-n5"] },
    { "kana": "くもる", "kanji": "曇る", "english": "to get cloudy", "jlpt": ["jlpt-n5"] },
    { "kana": "ごはん", "kanji": "ご飯", "english": "cooked rice", "jlpt": ["jlpt-n5"] },
    { "kana": "きいろい", "kanji": "黄色い", "english": "yellow", "jlpt": ["jlpt-n5"] },
    { "kana": "おかし", "kanji": "お菓子", "english": "confections", "jlpt": ["jlpt-n5"] },
    { "kana": "みがく", "kanji": "磨く", "english": "to polish", "jlpt": ["jlpt-n5"] },
    { "kana": "にぎやか", "kanji": "賑やか", "english": "bustling", "jlpt": ["jlpt-n5"] },
    { "kana": "なく", "kanji": "鳴く", "english": "to make sound (of an animal)", "jlpt": ["jlpt-n5"] },
    { "kana": "ゆうはん", "kanji": "夕飯", "english": "evening meal", "jlpt": ["jlpt-n5"] },
    { "kana": "はがき", "kanji": "葉書", "english": "postcard", "jlpt": ["jlpt-n5"] },
    { "kana": "あさごはん", "kanji": "朝ご飯", "english": "breakfast", "jlpt": ["jlpt-n5"] },
    { "kana": "ワイシャツ", "kanji": "Ｙシャツ", "english": "(formal) shirt", "jlpt": ["jlpt-n5"] },
    { "kana": "むっつ", "kanji": "六つ", "english": "six", "jlpt": ["jlpt-n5"] },
    { "kana": "おてあらい", "kanji": "お手洗い", "english": "toilet", "jlpt": ["jlpt-n1", "jlpt-n5"] },
    { "kana": "おまわりさん", "kanji": "お巡りさん", "english": "police officer", "jlpt": ["jlpt-n1", "jlpt-n5"] },
    { "kana": "れい", "kanji": "零", "english": "zero", "jlpt": ["jlpt-n5"] },
    { "kana": "さす", "kanji": "差す", "english": "to shine", "jlpt": ["jlpt-n5"] },
    { "kana": "はつか", "kanji": "２０日", "english": "20th day of the month", "jlpt": ["jlpt-n5"] },
    { "kana": "キロメートル", "kanji": "粁", "english": "kilometer", "jlpt": ["jlpt-n5"] },
    { "kana": "やっつ", "kanji": "八つ", "english": "eight", "jlpt": ["jlpt-n5"] },
    { "kana": "さらいねん", "kanji": "再来年", "english": "year after next", "jlpt": ["jlpt-n2", "jlpt-n5"] },
    { "kana": "マッチ", "kanji": "燐寸", "english": "match (for lighting a fire)", "jlpt": ["jlpt-n5"] },
    { "kana": "よく", "kanji": "良く", "english": "nicely", "jlpt": ["jlpt-n5"] },
    { "kana": "そこ", "kanji": "其処", "english": "there (place relatively near listener)", "jlpt": ["jlpt-n1", "jlpt-n5"] },
    { "kana": "ちいさな", "kanji": "小さな", "english": "small", "jlpt": ["jlpt-n5"] },
    { "kana": "こたえる", "kanji": "答える", "english": "to answer", "jlpt": ["jlpt-n5"] },
    { "kana": "もういちど", "kanji": "もう一度", "english": "once more", "jlpt": ["jlpt-n5"] },
    { "kana": "いる", "kanji": "要る", "english": "to need", "jlpt": ["jlpt-n5"] },
    { "kana": "せ", "kanji": "背", "english": "back", "jlpt": ["jlpt-n5"] },
    { "kana": "おべんとう", "kanji": "お弁当", "english": "bento", "jlpt": ["jlpt-n5"] },
    { "kana": "ばんごはん", "kanji": "晩御飯", "english": "dinner", "jlpt": ["jlpt-n5"] },
    { "kana": "ひるごはん", "kanji": "昼ご飯", "english": "lunch", "jlpt": ["jlpt-n5"] },
    { "kana": "でも", "english": "but", "jlpt": ["jlpt-n3", "jlpt-n5"] },
    { "kana": "など", "kanji": "等", "english": "et cetera", "jlpt": ["jlpt-n3", "jlpt-n5"] },
    { "kana": "クラス", "english": "class", "jlpt": ["jlpt-n5"] },
    { "kana": "プール", "english": "(swimming) pool", "jlpt": ["jlpt-n5"] },
    { "kana": "なか", "kanji": "中", "english": "inside", "jlpt": ["jlpt-n5"] },
    { "kana": "テレビ", "english": "television", "jlpt": ["jlpt-n5"] },
    { "kana": "コーヒー", "kanji": "珈琲", "english": "coffee", "jlpt": ["jlpt-n5"] },
    { "kana": "ホテル", "english": "hotel", "jlpt": ["jlpt-n5"] },
    { "kana": "ニュース", "english": "news", "jlpt": ["jlpt-n5"] },
    { "kana": "テーブル", "english": "table", "jlpt": ["jlpt-n5"] },
    { "kana": "カメラ", "english": "camera", "jlpt": ["jlpt-n5"] },
    { "kana": "タクシー", "english": "taxi", "jlpt": ["jlpt-n5"] },
    { "kana": "スポーツ", "english": "sport", "jlpt": ["jlpt-n5"] },
    { "kana": "ラジオ", "english": "radio", "jlpt": ["jlpt-n5"] },
    { "kana": "ペン", "english": "pen", "jlpt": ["jlpt-n2", "jlpt-n5"] },
    { "kana": "レストラン", "english": "restaurant (esp. Western-style)", "jlpt": ["jlpt-n5"] },
    { "kana": "テスト", "english": "examination", "jlpt": ["jlpt-n5"] },
    { "kana": "ベッド", "english": "bed", "jlpt": ["jlpt-n5"] },
    { "kana": "パン", "english": "bread", "jlpt": ["jlpt-n5"] },
    { "kana": "ナイフ", "english": "knife", "jlpt": ["jlpt-n5"] },
    { "kana": "シャツ", "english": "shirt (undergarment)", "jlpt": ["jlpt-n5"] },
    { "kana": "ネクタイ", "english": "tie", "jlpt": ["jlpt-n5"] },
    { "kana": "ギター", "english": "guitar", "jlpt": ["jlpt-n5"] },
    { "kana": "メートル", "kanji": "米", "english": "metre (unit of length)", "jlpt": ["jlpt-n5"] },
    { "kana": "セーター", "english": "sweater", "jlpt": ["jlpt-n5"] },
    { "kana": "アパート", "english": "apartment building", "jlpt": ["jlpt-n5"] },
    { "kana": "ポケット", "english": "pocket", "jlpt": ["jlpt-n5"] },
    { "kana": "バター", "english": "butter", "jlpt": ["jlpt-n5"] },
    { "kana": "キロ", "english": "kilo-", "jlpt": ["jlpt-n3", "jlpt-n5"] },
    { "kana": "スカート", "english": "skirt", "jlpt": ["jlpt-n5"] },
    { "kana": "レコード", "english": "record (e.g. LP)", "jlpt": ["jlpt-n5"] },
    { "kana": "エレベーター", "english": "elevator", "jlpt": ["jlpt-n5"] },
    { "kana": "ズボン", "kanji": "洋袴", "english": "trousers", "jlpt": ["jlpt-n5"] },
    { "kana": "ポスト", "english": "postbox", "jlpt": ["jlpt-n5"] },
    { "kana": "コピー", "english": "copy", "jlpt": ["jlpt-n3", "jlpt-n5"] },
    { "kana": "シャワー", "english": "shower", "jlpt": ["jlpt-n5"] },
    { "kana": "ハンカチ", "english": "handkerchief", "jlpt": ["jlpt-n5"] },
    { "kana": "おととい", "kanji": "一昨日", "english": "day before yesterday", "jlpt": ["jlpt-n2", "jlpt-n5"] },
    { "kana": "テープ", "english": "tape", "jlpt": ["jlpt-n5"] },
    { "kana": "ストーブ", "english": "(room) heater", "jlpt": ["jlpt-n5"] },
    { "kana": "カップ", "english": "cup (drinking vessel, measure, brassiere, prize, etc.)", "jlpt": ["jlpt-n5"] },
    { "kana": "テープレコーダー", "english": "tape recorder", "jlpt": ["jlpt-n5"] },
    { "kana": "ボールペン", "english": "ball-point pen", "jlpt": ["jlpt-n5"] },
    { "kana": "スプーン", "english": "spoon", "jlpt": ["jlpt-n5"] },
    { "kana": "スリッパ", "english": "slipper", "jlpt": ["jlpt-n5"] },
    { "kana": "しょうゆ", "kanji": "醤油", "english": "soy sauce", "jlpt": ["jlpt-n2", "jlpt-n5"] },
    { "kana": "はい", "english": "yes", "jlpt": ["jlpt-n5"] },
    { "kana": "ペット", "english": "pet", "jlpt": ["jlpt-n5"] },
    { "kana": "する", "kanji": "為る", "english": "to do", "jlpt": ["jlpt-n3", "jlpt-n5"] },
    { "kana": "あれ", "kanji": "彼", "english": "that", "jlpt": ["jlpt-n5"] },
    { "kana": "ついたち", "kanji": "１日", "english": "1st day of the month", "jlpt": ["jlpt-n5"] },
    { "kana": "みっか", "kanji": "３日", "english": "3rd day of the month", "jlpt": ["jlpt-n5"] },
    { "kana": "いつか", "kanji": "５日", "english": "5th day of the month", "jlpt": ["jlpt-n5"] },
    { "kana": "ふつか", "kanji": "２日", "english": "2nd day of the month", "jlpt": ["jlpt-n5"] },
    { "kana": "とおか", "kanji": "１０日", "english": "10th day of the month", "jlpt": ["jlpt-n5"] },
    { "kana": "むいか", "kanji": "６日", "english": "6th day of the month", "jlpt": ["jlpt-n5"] },
    { "kana": "ようか", "kanji": "８日", "english": "8th day of the month", "jlpt": ["jlpt-n5"] },
    { "kana": "ここのか", "kanji": "９日", "english": "9th day of the month", "jlpt": ["jlpt-n5"] },
    { "kana": "くる", "kanji": "来る", "english": "to come (spatially or temporally)", "jlpt": ["jlpt-n5"] },
    { "kana": "あと", "kanji": "後", "english": "behind", "jlpt": ["jlpt-n5"] },
    { "kana": "かいしゃ", "kanji": "会社", "english": "company", "jlpt": ["jlpt-n5"] },
    { "kana": "ひとり", "kanji": "一人", "english": "one person", "jlpt": ["jlpt-n3", "jlpt-n1", "jlpt-n5"] },
    { "kana": "ふたり", "kanji": "二人", "english": "two persons", "jlpt": ["jlpt-n1", "jlpt-n5"] },
    { "kana": "そば", "kanji": "側", "english": "near", "jlpt": ["jlpt-n3", "jlpt-n5"] },
    { "kana": "いいえ", "kanji": "否", "english": "no", "jlpt": ["jlpt-n3", "jlpt-n1", "jlpt-n5"] },
    { "kana": "からい", "kanji": "辛い", "english": "spicy", "jlpt": ["jlpt-n5"] },
    { "kana": "もん", "kanji": "門", "english": "gate", "jlpt": ["jlpt-n1", "jlpt-n5"] },
    { "kana": "かど", "kanji": "角", "english": "corner", "jlpt": ["jlpt-n5"] },
    { "kana": "まいつき", "kanji": "毎月", "english": "every month", "jlpt": ["jlpt-n5"] },
    { "kana": "しち", "kanji": "七", "english": "seven", "jlpt": ["jlpt-n3", "jlpt-n5"] },
    { "kana": "おばさん", "kanji": "伯母さん", "english": "aunt", "jlpt": ["jlpt-n2", "jlpt-n5"] },
    { "kana": "し", "kanji": "四", "english": "four", "jlpt": ["jlpt-n3", "jlpt-n5"] },
    { "kana": "おふろ", "kanji": "お風呂", "english": "bath", "jlpt": ["jlpt-n5"] },
    { "kana": "おさけ", "kanji": "お酒", "english": "alcohol", "jlpt": ["jlpt-n5"] },
    { "kana": "いりぐち", "kanji": "入口", "english": "entrance", "jlpt": ["jlpt-n1", "jlpt-n5"] },
    { "kana": "でぐち", "kanji": "出口", "english": "exit", "jlpt": ["jlpt-n5"] },
    { "kana": "おさら", "kanji": "お皿", "english": "plate", "jlpt": ["jlpt-n5"] },
    { "kana": "ここ", "kanji": "此処", "english": "here", "jlpt": ["jlpt-n3", "jlpt-n5"] },
    { "kana": "まえ", "kanji": "前", "english": "in front (of)", "jlpt": ["jlpt-n5"] },
    { "kana": "もう", "english": "now", "jlpt": ["jlpt-n5"] },
    { "kana": "どう", "kanji": "如何", "english": "how", "jlpt": ["jlpt-n1", "jlpt-n5"] },
    { "kana": "かた", "kanji": "方", "english": "direction", "jlpt": ["jlpt-n5"] },
    { "kana": "まだ", "kanji": "未だ", "english": "still", "jlpt": ["jlpt-n3", "jlpt-n1", "jlpt-n5"] },
    { "kana": "もっと", "english": "(some) more", "jlpt": ["jlpt-n5"] },
    { "kana": "いつ", "kanji": "何時", "english": "when", "jlpt": ["jlpt-n1", "jlpt-n5"] },
    { "kana": "パーティー", "english": "party (social gathering)", "jlpt": ["jlpt-n5"] },
    { "kana": "ほか", "kanji": "他", "english": "other (place, thing, person)", "jlpt": ["jlpt-n3", "jlpt-n5"] },
    { "kana": "つぎ", "kanji": "次", "english": "next", "jlpt": ["jlpt-n5"] },
    { "kana": "ドア", "english": "door (Western-style, car, etc.)", "jlpt": ["jlpt-n5"] },
    { "kana": "どちら", "kanji": "何方", "english": "which way", "jlpt": ["jlpt-n1", "jlpt-n5"] },
    { "kana": "だれか", "kanji": "誰か", "english": "someone", "jlpt": ["jlpt-n3", "jlpt-n5"] },
    { "kana": "あく", "kanji": "開く", "english": "to open (e.g. doors)", "jlpt": ["jlpt-n4", "jlpt-n5"] },
    { "kana": "どうぞ", "english": "please", "jlpt": ["jlpt-n5"] },
    { "kana": "こんな", "english": "this sort of", "jlpt": ["jlpt-n5"] },
    { "kana": "した", "kanji": "下", "english": "below", "jlpt": ["jlpt-n5"] },
    { "kana": "そして", "kanji": "而して", "english": "and", "jlpt": ["jlpt-n3", "jlpt-n1", "jlpt-n5"] },
    { "kana": "ゆっくり", "english": "slowly", "jlpt": ["jlpt-n3", "jlpt-n5"] },
    { "kana": "さあ", "english": "come (on)", "jlpt": ["jlpt-n5"] },
    { "kana": "どうも", "english": "thank you", "jlpt": ["jlpt-n5"] },
    { "kana": "じゃあ", "english": "then", "jlpt": ["jlpt-n5"] },
    { "kana": "それから", "kanji": "其れから", "english": "and then", "jlpt": ["jlpt-n1", "jlpt-n5"] },
    { "kana": "ええ", "english": "yes", "jlpt": ["jlpt-n5"] },
    { "kana": "ノート", "english": "notebook", "jlpt": ["jlpt-n5"] },
    { "kana": "ボタン", "kanji": "釦", "english": "button (clothing)", "jlpt": ["jlpt-n5"] },
    { "kana": "デパート", "english": "department store", "jlpt": ["jlpt-n5"] },
    { "kana": "トイレ", "english": "toilet", "jlpt": ["jlpt-n5"] },
    { "kana": "それでは", "english": "well, ...", "jlpt": ["jlpt-n1", "jlpt-n5"] },
    { "kana": "あさって", "kanji": "明後日", "english": "day after tomorrow", "jlpt": ["jlpt-n3", "jlpt-n1", "jlpt-n5"] },
    { "kana": "どれ", "kanji": "何れ", "english": "which (of three or more)", "jlpt": ["jlpt-n3", "jlpt-n1", "jlpt-n5"] },
    { "kana": "はたち", "kanji": "２０歳", "english": "20 years old", "jlpt": ["jlpt-n3", "jlpt-n5"] },
    { "kana": "あちら", "kanji": "彼方", "english": "that way", "jlpt": ["jlpt-n1", "jlpt-n5"] },
    { "kana": "では", "english": "then", "jlpt": ["jlpt-n3", "jlpt-n5"] },
    { "kana": "フィルム", "english": "film", "jlpt": ["jlpt-n5"] },
    { "kana": "よっか", "kanji": "４日", "english": "4th day of the month", "jlpt": ["jlpt-n5"] },
    { "kana": "ぬるい", "kanji": "温い", "english": "lukewarm", "jlpt": ["jlpt-n5"] },
    { "kana": "カレンダー", "english": "calendar", "jlpt": ["jlpt-n5"] },
    { "kana": "なのか", "kanji": "７日", "english": "7th day of the month", "jlpt": ["jlpt-n1", "jlpt-n5"] }, 
    { "kana": "そうして", "kanji": "然うして", "english": "and", "jlpt": ["jlpt-n2", "jlpt-n1", "jlpt-n5"] }, 
    { "kana": "グラム", "kanji": "瓦", "english": "gram", "jlpt": ["jlpt-n5"] }, 
    { "kana": "キログラム", "kanji": "瓩", "english": "kilogram", "jlpt": ["jlpt-n5"] }, 
    { "kana": "すぐに", "kanji": "直ぐに", "english": "immediately", "jlpt": ["jlpt-n5"] }, 
    { "kana": "ひとつき", "kanji": "一月", "english": "one month", "jlpt": ["jlpt-n5"] }, 
    { "kana": "あの", "english": "say", "jlpt": ["jlpt-n5"] }, 
    { "kana": "あき", "kanji": "秋", "english": "autumn", "jlpt": ["jlpt-n5"] }, 
    { "kana": "じびき", "kanji": "字引", "english": "dictionary", "jlpt": ["jlpt-n5"] }, 
    { "kana": "カレー", "kanji": "咖哩", "english": "curry (esp. Japanese curry)", "jlpt": ["jlpt-n5"] }, 
    { "kana": "バス", "english": "bus", "jlpt": ["jlpt-n5"] }, 
    { "kana": "サン", "kanji": "三", "english": "three", "jlpt": ["jlpt-n5"] }, 
    { "kana": "コート", "english": "coat", "jlpt": ["jlpt-n5"] }, 
    { "kana": "コップ", "kanji": "洋杯", "english": "glass (drinking vessel)", "jlpt": ["jlpt-n5"] }, 
    { "kana": "フォーク", "english": "fork", "jlpt": ["jlpt-n5"] }, 
    { "kana": "ラジカセ", "english": "radio-cassette player", "jlpt": ["jlpt-n5"] }, 
    { "kana": "マッチ", "english": "match (contest)", "jlpt": ["jlpt-n5"] }
]